use_frameworks!

target 'szhKit_Example' do
  pod 'szhKit', :path => '../'
  
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'szhKit_Tests' do
    inherit! :search_paths

    
  end
end
